### ISSUE TITLE
AttributeError: 

### ISSUE THREAD

**Issue by TheKrafter** [RoseSMP/Tiramisu#58]
### Description

On start, the mod_rightclick module cannot load

<details>

```
2023-08-01 20:47:00.286 | INFO     | __main__:<module>:25 - Successfully found config/config.yml!
2023-08-01 20:47:00.292 | SUCCESS  | libs.utility:verify_config:162 - Config did not need repaired!
2023-08-01 20:47:00.294 | INFO     | __main__:<module>:38 - Successfully loaded config/config.yml: {'cog_dontload': ['bad_example.py'], 'debug': True, 'discord': {'co_owners': [883031597291569193], 'owner': 705150784941064293, 'roles': {'staff': 0}, 'testing_guild': 1035313572638638110, 'token': 'REDACTED'}, 'fizzdev=catboy': True, 'messages': {'error': '⚠️ **An Error Occured!** ``` [[error]] ``` Please report this to the devs.', 'noperm': '**🚫 No permission**', 'noperm_log': '[[user]] (ID: [[user_id]]) tried to run "[[command]]" but doesnt have permission!'}, 'mysql': {'db': 'tiramisu', 'host': 'localhost', 'pass': 'ImACatb0y!', 'port': '3306', 'user': 'tiramisu'}, 'storage': 'sqlite'}
2023-08-01 20:47:00.294 | DEBUG    | asyncio.selector_events:__init__:54 - Using selector: EpollSelector
2023-08-01 20:47:00.295 | WARNING  | nextcord.client:__init__:336 - PyNaCl is not installed, voice will NOT be supported
2023-08-01 20:47:00.295 | DEBUG    | nextcord.client:event:1275 - on_ready has successfully been registered as an event
2023-08-01 20:47:00.298 | DEBUG    | cogs.admin:setup:125 - Setup cog "admin"
2023-08-01 20:47:00.301 | DEBUG    | cogs.announce:setup:68 - Setup cog "announce"
2023-08-01 20:47:00.304 | DEBUG    | cogs.utilities:setup:100 - Setup cog "utilities"
2023-08-01 20:47:00.320 | DEBUG    | cogs.help:setup:53 - Setup cog "help"
Traceback (most recent call last):
  File "/home/tiramisu/.local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 741, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/tiramisu/Tiramisu/cogs/mod_rightclick.py", line 13, in <module>
    from libs import moderation, utility, modals
  File "/home/tiramisu/Tiramisu/libs/modals.py", line 100, in <module>
    class BugReportModal(nextcord.ui.Modal):
  File "/home/tiramisu/Tiramisu/libs/modals.py", line 101, in BugReportModal
    def __init__(self, channel: nextcord.Channel, questions):
                                ^^^^^^^^^^^^^^^^
AttributeError: module 'nextcord' has no attribute 'Channel'. Did you mean: 'channel'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tiramisu/Tiramisu/bot.py", line 143, in <module>
    bot.load_extension(f'cogs.{filename[:-3]}')
  File "/home/tiramisu/.local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 863, in load_extension
    self._load_from_module_spec(spec, name, extras=extras)
  File "/home/tiramisu/.local/lib/python3.11/site-packages/nextcord/ext/commands/bot.py", line 744, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
nextcord.ext.commands.errors.ExtensionFailed: Extension 'cogs.mod_rightclick' raised an error: AttributeError: module 'nextcord' has no attribute 'Channel'
```

</details>

### Steps to reproduce

1. Run 
2. AttributeError

### Platform and Version
**Operating System:** 

Linux 

**CPU Archetecture:** 

x86_64

**Python Version:** 

Python 3.11.4

**Tiramisu Version:**  

Check only those that apply
- [x] I am running straight from git 
  - Branch: dev-report_modals
  
- [ ] I am running a release downloaded from the releases page
  - Release number:

**Comment by TheKrafter** [comment]
When disabling the cog, another cog throws the same error. Here is a list of other cogs that throw this error after the previous ones do the same:
- debug
- applications
- tickets
- reporting

**Comment by TheKrafter** [comment]
This does not happen in the main branch
